

// Test file generated by C2E https://community.modlycrew/c2e for use with cypress

// Helpers for Object validation
import Ajv from "ajv";
const ajv = new Ajv({ $data: true, allErrors: true, allowMatchingProperties: true, });
import addFormats from "ajv-formats";
addFormats(ajv);
require("ajv-merge-patch")(ajv);
ajv.addKeyword("$version");
function validateObject(objectToValidate, schema) {
    expect(objectToValidate, "Schema => " + JSON.stringify(schema)).to.equal(ajv.validate(schema.$id, objectToValidate) ? objectToValidate : ajv.errors.filter(e => e.keyword != "$merge"));
}

// Hoisted Imports
import * as ExampleImports from '../../example-imports.js';

// Hoisted Variables
let varSB1;
let schema;
let varScene1;
let varUserStory1;
let varUserStory2;
let data;

// Tests
describe("🏢 0.0.1 - Example Capability - 2nd Story Board ",()=>{
         describe("🔧 actions", () => {
    it("🔧 Simple variable assignment e.g. varSB1 = 4 * 4", () => {
        varSB1 = 4 * 4
        cy.log("varSB1 => " + JSON.stringify(varSB1))
    });
    it("🔧 Import modules", () => {
        cy.log("import * as ExampleImports from '../../example-imports.js' hoisted to Imports");
    });
    it("🔧 Load Schema", () => {
          schema = {
      $id: "test",
      type: "object",
      properties: {
          foo: { type: "integer" },
          bar: { type: "string" }
      },
      required: ["foo"],
      additionalProperties: true
  }
  ajv.addSchema(schema, schema.$id)
        cy.log("  schema => " + JSON.stringify(  schema))
    });
    }); 
    describe("📃 scenes", () => {
            describe("1st Scene: ", () => {
            describe("🔧 actions", () => {
    it("🔧 Set varScene1 to 'Scene level Variable'", () => {
        varScene1 = 'Scene level Variable'
        cy.log("varScene1 => " + JSON.stringify(varScene1))
    });
    }); 
    describe("👩‍🏭 user stories", () => {
            describe("User Story 1: ", () => {
            describe("🔧 actions", () => {
    it("🔧 Set varUserStory1 to .standardExample()", () => {
        varUserStory1 = ExampleImports.standardExample()
        cy.log("varUserStory1 => " + JSON.stringify(varUserStory1))
    });
    it("🔧 Set varUserStory2 to .asyncExample()'", () => {
        cy.wrap(null).then(() => {
            return (new Cypress.Promise((resolve, reject) => { resolve(
                ExampleImports.asyncExample('Provided Import Async Example Value')
            )})).then((obj) => { varUserStory2 = obj })
        })
        cy.log("varUserStory2 => " + JSON.stringify(varUserStory2))
    });
    it("🔧 Set test Data Object", () => {
          data = { foo: 1, bar: "abc", baz: null}
        cy.log("  data => " + JSON.stringify(  data))
    });
    }); 
    describe("🚧 expectations", () => {
    it("🚧 Check varSB1 value", () => {
        expect(varSB1,"/").to.equal(16)
    });
    it("🚧 Check varScene1 value", () => {
        expect(varScene1,"/").to.equal('Scene level Variable')
    });
    it("🚧 Check varUserStory1 value", () => {
        expect(varUserStory1,"/").to.equal('Default Import Example Value')
    });
    it("🚧 Check varUserStory2 value", () => {
        expect(varUserStory2,"/").to.equal('Provided Import Async Example Value')
    });
    it("🔧 Validate Object", () => {
        validateObject(data, schema)
        cy.log("validateObject(data, schema) => " + JSON.stringify(validateObject(data, schema)))
    });
    }); 
    });
    describe("User Story 2: ", () => {
            describe("🚧 expectations", () => {
    it("🔧 1st Expectation - write to console log...", () => {
        console.log('Example...','User Story 2 - 1st Expectation')
    });
    it("🔧 2nd Expectation - write to cypress log...", () => {
        cy.log('Example...','User Story 2 - 2nd Expectation')
    });
    it("🚧 1st Expectation - check varSB1", () => {
        cy.log("1 code pending");
    });
    it("🚧 2nd Expectation", () => {
        cy.log("2 code pending");
    });
    }); 
    });
    });
    });
    describe("2nd Scene: ", () => {
            describe("👩‍🏭 user stories", () => {
            describe("User Story 1: ", () => {
            describe("🚧 expectations", () => {
    it("🚧 1st Expectation", () => {
        cy.log("1 code pending");
    });
    it("🚧 2nd Expectation", () => {
        cy.log("2 code pending");
    });
    it("🚧 3rd Expectation", () => {
        cy.log("3 code pending");
    });
    it("🚧 4th Expectation", () => {
        cy.log("4 code pending");
    });
    }); 
    });
    describe("User Story 2: ", () => {
            describe("🚧 expectations", () => {
    it("🚧 1st Expectation", () => {
        cy.log("1 code pending");
    });
    it("🚧 2nd Expectation", () => {
        cy.log("2 code pending");
    });
    }); 
    });
    });
    });
    });
});