
// @js-check
import { test } from '@playwright/test';
import { expect } from 'chai';

// Test file generated by C2E https://community.modlycrew/c2e for use with playwright

// Helpers for Object validation
import Ajv from "ajv";
const ajv = new Ajv({ $data: true, allErrors: true, allowMatchingProperties: true, });
import addFormats from "ajv-formats";
addFormats(ajv);
require("ajv-merge-patch")(ajv);
ajv.addKeyword("$version");
function validateObject(objectToValidate, schema) {
    expect(objectToValidate, "Schema => " + JSON.stringify(schema)).to.equal(ajv.validate(schema.$id, objectToValidate) ? objectToValidate : ajv.errors.filter(e => e.keyword != "$merge"));
}

// Hoisted Imports
import * as ExampleImports from '../../example-imports.js';
import * as SecondImport from '../../example-imports.js';

// Hoisted Variables
let varSB1;
let schema;
let varScene1;
let varUserStory1;
let varUserStory2;
let data;

// Tests
test.describe("🏢 0.0.1 - Example Capability - 1st Story Board ",()=>{
         test.describe("📃 scenes", async () => {
            test.describe("Storyboard setup: ", async () => {
            test.describe("🔧 actions", async () => {
    test("🔧 Simple variable assignment e.g.  varSB1 = 4 * 4", async () => {
        varSB1 = 4 * 4
        console.log("varSB1 => " + JSON.stringify(varSB1))
    });
    test("🔧 Import modules", async () => {
        console.log("import * as ExampleImports from '../../example-imports.js' hoisted to Imports");
    });
    test("🔧 Import other modules", async () => {
        console.log("import * as SecondImport from '../../example-imports.js' hoisted to Imports");
    });
    test("🔧 Load Schema", async () => {
          schema = {
      $id: "test",
      type: "object",
      properties: {
          foo: { type: "integer" },
          bar: { type: "string" }
      },
      required: ["foo"],
      additionalProperties: false
  }
  ajv.addSchema(schema, schema.$id)
        console.log("  schema => " + JSON.stringify(  schema))
    });
    }); 
    });
    test.describe("1st Scene: ", async () => {
            test.describe("🔧 actions", async () => {
    test("🔧 Set varScene1 to 'Scene level Variable'", async () => {
        varScene1 = 'Scene level Variable'
        console.log("varScene1 => " + JSON.stringify(varScene1))
    });
    }); 
    test.describe("👩‍🏭 user stories", async () => {
            test.describe("1st User Story: ", async () => {
            test.describe("🔧 actions", async () => {
    test("🔧 Set varUserStory1 to .standardExample()", async () => {
        varUserStory1 = ExampleImports.standardExample()
        console.log("varUserStory1 => " + JSON.stringify(varUserStory1))
    });
    test("🔧 Set varUserStory2 to .asyncExample()'", async () => {
        varUserStory2 = await ExampleImports.asyncExample('Provided Import Async Example Value')
        console.log("varUserStory2 => " + JSON.stringify(varUserStory2))
    });
    test("🔧 Set test Data Object", async () => {
          data = { foo: 1, bar: "abc"}
        console.log("  data => " + JSON.stringify(  data))
    });
    }); 
    test.describe("🚧 expectations", async () => {
    test("🚧 Check varSB1 value", async () => {
        expect(varSB1,"/").to.equal(16)
    });
    test("🚧 Check varScene1 value", async () => {
        expect(varScene1,"/").to.equal('Scene level Variable')
    });
    test("🚧 Check varUserStory1 value", async () => {
        expect(varUserStory1,"/").to.equal('Default Import Example Value')
    });
    test("🚧 Check varUserStory2 value", async () => {
        expect(varUserStory2,"/").to.equal('Provided Import Async Example Value')
    });
    test("🔧 Validate Object", async () => {
        validateObject(data, schema)
        console.log("validateObject(data, schema) => " + JSON.stringify(validateObject(data, schema)))
    });
    }); 
    });
    test.describe("User Story 2: ", async () => {
            test.describe("🚧 expectations", async () => {
    test("🔧 1st Expectation - write to console log...", async () => {
        console.log('Example...','User Story 2 - 1st Expectation')
    });
    test("🔧 2nd Expectation - write to cypress log (or console.log if )...", async () => {
        console.log('Example...','User Story 2 - 2nd Expectation')
    });
    test("🚧 3rd Expectation - check varSB1", async () => {
        console.log("3 code pending");
    });
    test("🚧 4th Expectation", async () => {
        console.log("4 code pending");
    });
    }); 
    });
    });
    });
    test.describe("2nd Scene: ", async () => {
            test.describe("👩‍🏭 user stories", async () => {
            test.describe("User Story 1: ", async () => {
            test.describe("🚧 expectations", async () => {
    test("🚧 1st Expectation", async () => {
        console.log("1 code pending");
    });
    test("🚧 2nd Expectation", async () => {
        console.log("2 code pending");
    });
    test("🚧 3rd Expectation", async () => {
        console.log("3 code pending");
    });
    test("🚧 4th Expectation", async () => {
        console.log("4 code pending");
    });
    }); 
    });
    test.describe("User Story 2: ", async () => {
            test.describe("🚧 expectations", async () => {
    test("🚧 1st Expectation", async () => {
        console.log("1 code pending");
    });
    test("🚧 2nd Expectation", async () => {
        console.log("2 code pending");
    });
    }); 
    });
    });
    });
    });
});